sudo: false
language: rust
dist: trusty
git:
  depth: 3
branches:
  only:
  - master
rust:
- stable
- beta
- nightly
matrix:
  include:
  - os: linux
    rust: 1.12.0
    script: cargo test
before_install:
- openssl aes-256-cbc -K $encrypted_844d74e86345_key -iv $encrypted_844d74e86345_iv
  -in Config.toml.enc -out Config.toml -d
script:
- cargo build --verbose
- cargo test --verbose
- cargo doc --no-deps
os:
- linux
- osx
