language: rust
sudo: false

git:
  depth: 3

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev # optional: only required for the --verify flag of coveralls

before_install:
- openssl aes-256-cbc -K $encrypted_844d74e86345_key -iv $encrypted_844d74e86345_iv -in Config.toml.enc -out Config.toml -d

rust:
  - stable
  - beta
  - nightly
  - 1.12.0

os:
  - linux
  - osx

script:
    - cargo build --verbose
    - cargo test --verbose
    - cargo bench --verbose
    - cargo doc --no-deps

after_success: |
    # should be more strict about kcov version
    wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
    tar xzf master.tar.gz &&
    mkdir kcov-master/build && cd kcov-master/build &&
    cmake .. && make && make install DESTDIR=../tmp && cd ../.. &&
    ls target/debug &&
    ./kcov-master/tmp/usr/local/bin/kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo,/usr/lib --verify target/cov target/debug/ovh-*
